=== mzampetakis/softwarecrafters-website/conferences_schema_v2.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Schema for Conference JSON Files",
  "type": "object",
  "properties": {
    "$schema": {
      "description": "Schema reference",
      "type": "string",
      "format": "uri"
    },
    "name": {
      "description": "Name of your community",
      "type": "string"
    },
    "description": {
      "description": "A headline for your conference",
      "type": "string"
    },
    "url": {
      "description": "URL leading to further information about your conference",
      "type": "string",
      "format": "uri"
    },
    "code-of-conduct": {
      "description": "URL to your code of conduct",
      "type": "string"
    },
    "health-policy": {
      "description": "A brief summary of the measures taken with regards to attendee health.",
      "type": "string"
    },
    "next-date": {
      "description": "The next time your conference is taking place",
      "type": "object",
      "properties": {
        "start": {
          "description": "The day your conference starts in YYYY-MM-DD format",
          "$ref": "#/definitions/date"
        },
        "end": {
          "description": "The day your conference ends in YYYY-MM-DD format",
          "$ref": "#/definitions/date"
        }
      },
      "required": ["start", "end"],
      "additionalProperties": false
    },
    "location": {
      "oneOf": [
        {
          "$ref": "#/definitions/real_location"
        },
        {
          "$ref": "#/definitions/virtual_location"
        }
      ]
    },
    "icon": {
      "description": "The relative url to an icon in 64x64 PNG format. Should be places in /target/icons/",
      "type": "string"
    }
  },
  "additionalProperties": false,
  "required": ["name", "url", "location", "code-of-conduct"],
  "definitions": {
    "date": {
      "type": "string",
      "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}$"
    },
    "virtual_location": {
      "type": "string",
      "enum": ["virtual"]
    },
    "real_location": {
      "description": "Information about where to place your conference on the map",
      "type": "object",
      "properties": {
        "city": {
          "type": "string"
        },
        "country": {
          "type": "string"
        },
        "coordinates": {
          "type": "object",
          "description": "Long/Lat values of where to place your community.",
          "properties": {
            "lat": {
              "description": "Latitude",
              "type": "number",
              "minimum": -90,
              "maximum": 90
            },
            "lng": {
              "description": "Longitude",
              "type": "number",
              "minimum": -180,
              "maximum": 180
            }
          },
          "additionalProperties": false,
          "required": ["lat", "lng"]
        }
      },
      "additionalProperties": false,
      "required": ["coordinates"]
    }
  }
}

=== mzampetakis/softwarecrafters-website/conferences/socrates-day-ch.json
{
  "$schema": "https://softwarecrafters.org/conferences_schema_v2.json",
  "name": "SoCraTes Day Switzerland",
  "url": "http://socrates-day.ch/",
  "code-of-conduct": "https://github.com/socrates-ch/socrates-day/wiki/Code-of-Conduct",
  "next-date": {
    "start": "2025-09-19",
    "end": "2025-09-19"
  },
  "location": {
    "city": "ZÃ¼rich",
    "country": "Switzerland",
    "coordinates": {
      "lat": 47.36742,
      "lng": 8.55399
    }
  }
}

=== mzampetakis/softwarecrafters-website/conferences/socrates-fr-rennes.json
{
  "$schema": "https://softwarecrafters.org/conferences_schema_v2.json",
  "name": "SoCraTes Rennes",
  "url": "https://socrates-rennes.github.io/",
  "code-of-conduct": "https://socrates-rennes.github.io/#a-propos",
  "next-date": {
    "start": "2026-03-31",
    "end": "2026-03-31"
  },
  "location": {
    "city": "Rennes",
    "country": "France",
    "coordinates": {
      "lat": 48.1151,
      "lng": -1.6405
    }
  }
}

=== mzampetakis/softwarecrafters-website/conferences/socrates-be.json
{
  "$schema": "https://softwarecrafters.org/conferences_schema_v2.json",
  "name": "SoCraTes Belgium",
  "url": "http://socratesbe.org/",
  "code-of-conduct": "https://confcodeofconduct.com/",
  "next-date": {
    "start": "2025-10-09",
    "end": "2025-10-12"
  },
  "location": {
    "city": "La Roche-En-Ardenne",
    "country": "Belgium",
    "coordinates": { "lat": 50.17952, "lng": 5.58305 }
  }
}

=== mzampetakis/softwarecrafters-website/conferences/socrates-austria.json
{
  "$schema": "https://softwarecrafters.org/conferences_schema_v2.json",
  "name": "SoCraTes Austria 2025",
  "url": "https://socrates-conference.at/",
  "code-of-conduct": "https://socrates-conference.at/code-of-conduct/",
  "next-date": {
    "start": "2026-09-25",
    "end": "2026-09-26"
  },
  "location": {
    "city": "Linz",
    "country": "Austria",
    "coordinates": {
      "lat": 48.29074,
      "lng": 14.28827
    }
  }
}
