=== mzampetakis/softwarecrafters-website/conferences_schema_v2.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Schema for Conference JSON Files",
  "type": "object",
  "properties": {
    "$schema": {
      "description": "Schema reference",
      "type": "string",
      "format": "uri"
    },
    "name": {
      "description": "Name of your community",
      "type": "string"
    },
    "description": {
      "description": "A headline for your conference",
      "type": "string"
    },
    "url": {
      "description": "URL leading to further information about your conference",
      "type": "string",
      "format": "uri"
    },
    "code-of-conduct": {
      "description": "URL to your code of conduct",
      "type": "string"
    },
    "health-policy": {
      "description": "A brief summary of the measures taken with regards to attendee health.",
      "type": "string"
    },
    "next-date": {
      "description": "The next time your conference is taking place",
      "type": "object",
      "properties": {
        "start": {
          "description": "The day your conference starts in YYYY-MM-DD format",
          "$ref": "#/definitions/date"
        },
        "end": {
          "description": "The day your conference ends in YYYY-MM-DD format",
          "$ref": "#/definitions/date"
        }
      },
      "required": ["start", "end"],
      "additionalProperties": false
    },
    "location": {
      "oneOf": [
        {
          "$ref": "#/definitions/real_location"
        },
        {
          "$ref": "#/definitions/virtual_location"
        }
      ]
    },
    "icon": {
      "description": "The relative url to an icon in 64x64 PNG format. Should be places in /target/icons/",
      "type": "string"
    }
  },
  "additionalProperties": false,
  "required": ["name", "url", "location", "code-of-conduct"],
  "definitions": {
    "date": {
      "type": "string",
      "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}$"
    },
    "virtual_location": {
      "type": "string",
      "enum": ["virtual"]
    },
    "real_location": {
      "description": "Information about where to place your conference on the map",
      "type": "object",
      "properties": {
        "city": {
          "type": "string"
        },
        "country": {
          "type": "string"
        },
        "coordinates": {
          "type": "object",
          "description": "Long/Lat values of where to place your community.",
          "properties": {
            "lat": {
              "description": "Latitude",
              "type": "number",
              "minimum": -90,
              "maximum": 90
            },
            "lng": {
              "description": "Longitude",
              "type": "number",
              "minimum": -180,
              "maximum": 180
            }
          },
          "additionalProperties": false,
          "required": ["lat", "lng"]
        }
      },
      "additionalProperties": false,
      "required": ["coordinates"]
    }
  }
}

=== mzampetakis/softwarecrafters-website/conferences/socrates-de.json
{
  "$schema": "https://softwarecrafters.org/conferences_schema_v2.json",
  "name": "SoCraTes Germany",
  "url": "https://www.socrates-conference.de/",
  "code-of-conduct": "https://www.socrates-conference.de/values",
  "health-policy": "Lateral flow tests at sign-in and afterwards provided for daily self-administered testing.",
  "next-date": {
    "start": "2026-08-27",
    "end": "2026-08-30"
  },
  "location": {
    "city": "Soltau",
    "country": "Germany",
    "coordinates": {
      "lat": 53.00146,
      "lng": 9.85963
    }
  }
}

=== mzampetakis/softwarecrafters-website/conferences/socrates-day-berlin.json
{
  "$schema": "https://softwarecrafters.org/conferences_schema_v2.json",
  "name": "SoCraTes Day Berlin",
  "url": "http://www.socratesday.berlin",
  "code-of-conduct": "http://www.socratesday.berlin",
  "health-policy": "self-test and show result during registration",
  "next-date": {
    "start": "2025-09-13",
    "end": "2025-09-13"
  },
  "location": {
    "city": "Berlin",
    "country": "Germany",
    "coordinates": {
      "lat": 52.50892,
      "lng": 13.42169
    }
  },
  "icon": "icons/socratesdayber.png"
}

=== mzampetakis/softwarecrafters-website/conferences/socrates-fr.json
{
  "$schema": "https://softwarecrafters.org/conferences_schema_v2.json",
  "name": "SoCraTes France",
  "url": "https://socrates-fr.github.io/",
  "code-of-conduct": "https://socrates-fr.github.io/#portfolioModal2",
  "next-date": {
    "start": "2026-03-26",
    "end": "2026-03-29"
  },
  "location": {
    "city": "Uchaux",
    "country": "France",
    "coordinates": {
      "lat": 49.26762,
      "lng": 1.89751
    }
  }
}

=== mzampetakis/softwarecrafters-website/conferences/scunconf.json
{
  "$schema": "https://softwarecrafters.org/conferences_schema_v2.json",
  "name": "Software Crafters Unconference Online",
  "url": "http://scunconf.com/",
  "code-of-conduct": "https://scunconf.com/#coc",
  "next-date": {
    "start": "2026-02-06",
    "end": "2026-02-06"
  },
  "location": "virtual"
}

=== mzampetakis/softwarecrafters-website/conferences/socrates-uk.json
{
  "name": "SoCraTes UK",
  "url": "https://socratesuk.org/",
  "code-of-conduct": "https://socratesuk.org/code_of_conduct.html",
  "next-date": {
    "start": "2026-06-18",
    "end": "2026-06-21"
  },
  "health-policy": "Masks recommended, daily tests mandatory (both provided by us) and air filtering",
  "location": {
    "coordinates": {
      "lat": 51.608682,
      "lng": -1.315764
    }
  },
  "icon": "icons/socrates-uk.png"
}

=== mzampetakis/softwarecrafters-website/conferences/socrates-day-franconia.json
{
  "$schema": "https://softwarecrafters.org/conferences_schema_v2.json",
  "name": "SoCraTes Day Franconia",
  "url": "http://socrates-day-franken.de/",
  "code-of-conduct": "http://socrates-day-franken.de/",
  "next-date": {
    "start": "2019-09-28",
    "end": "2019-09-28"
  },
  "location": {
    "city": "NÃ¼rnberg",
    "country": "Germany",
    "coordinates": {
      "lat": 49.453445,
      "lng": 11.046401
    }
  }
}

=== mzampetakis/softwarecrafters-website/conferences/jalba-unconf.json
{
  "name": "JAlba",
  "url": "http://jalba.scot/",
  "code-of-conduct": "http://jalba.scot/jalba-code-of-conduct/",
  "location": {
    "city": "Edinburgh",
    "country": "Scotland",
    "coordinates": {
      "lat": 55.9533,
      "lng": -3.188267
    }
  },
  "next-date": {
    "start": "2026-05-14",
    "end": "2026-05-16"
  }
}

=== mzampetakis/softwarecrafters-website/conferences/open-security-conference.json
{
  "name": "Open Security Conference",
  "url": "https://opensecurityconference.org/",
  "code-of-conduct": "https://opensecurityconference.org/about/values/",
  "next-date": {
    "start": "2026-11-05",
    "end": "2026-11-08"
  },
  "location": {
    "city": "RÃ¼ckersbach",
    "coordinates": { "lat": 50.06738, "lng": 9.10824 }
  }
}
